# Generated by Django 6.0 on 2025-12-14 09:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('portal', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='resource',
            name='domain',
        ),
        migrations.AlterModelOptions(
            name='resource',
            options={'verbose_name_plural': 'Resources'},
        ),
        migrations.RemoveField(
            model_name='resource',
            name='company_name',
        ),
        migrations.AddField(
            model_name='resource',
            name='url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='groups',
            field=models.ManyToManyField(blank=True, help_text='The groups this user belongs to.', related_name='custom_user_groups', to='auth.group', verbose_name='groups'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='user_permissions',
            field=models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='custom_user_permissions', to='auth.permission', verbose_name='user permissions'),
        ),
        migrations.AlterField(
            model_name='resource',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='portal.customuser'),
        ),
        migrations.AlterField(
            model_name='resource',
            name='resource_type',
            field=models.CharField(choices=[('PROJECT', 'Project'), ('PROGRAM', 'Program')], max_length=10),
        ),
        migrations.DeleteModel(
            name='Domain',
        ),
    ]
