# Generated by Django 6.0 on 2025-12-07 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='companyprogram',
            old_name='name',
            new_name='company_name',
        ),
        migrations.RenameField(
            model_name='companyprogram',
            old_name='description',
            new_name='eligibility_criteria',
        ),
        migrations.RemoveField(
            model_name='companyprogram',
            name='company',
        ),
        migrations.RemoveField(
            model_name='companyprogram',
            name='link',
        ),
        migrations.AddField(
            model_name='companyprogram',
            name='program_name',
            field=models.CharField(default='General', max_length=200),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='projectidea',
            name='domain',
            field=models.CharField(max_length=100),
        ),
    ]
