# Generated by Django 6.0 on 2025-12-15 06:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0003_alter_resource_created_by_alter_resource_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CompanyProgram',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('company_name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('program_type', models.CharField(choices=[('INTERNSHIP', 'Internship/Fellowship'), ('CONTEST', 'Coding Contest/Challenge'), ('TRAINING', 'Training/Bootcamp'), ('OTHER', 'Other Program')], max_length=20)),
                ('link', models.URLField()),
                ('deadline', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Company Programs',
                'ordering': ['-created_at'],
            },
        ),
    ]
